//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.CLAnnualCourses = new HashSet<CLAnnualCourse>();
        }
        public Account(int accountId, String userName, String passWord, int? profileId, int? roleId)
        {
            this.accountId = (int)accountId;
            this.userName = userName;
            this.userPassword = passWord;
            this.profileId = (int)profileId;
            this.roleId = (int)roleId;
        }
        public int accountId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public Nullable<int> profileId { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<CLAnnualCourse> CLAnnualCourses { get; set; }
    }
}
