//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AnnualCourses = new HashSet<AnnualCourse>();
            this.Comments = new HashSet<Comment>();
            this.Faculties = new HashSet<Faculty>();
            this.Faculties1 = new HashSet<Faculty>();
            this.Faculties2 = new HashSet<Faculty>();
        }
    
        public int accountId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public Nullable<int> profileId { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<AnnualCourse> AnnualCourses { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<Faculty> Faculties1 { get; set; }
        public virtual ICollection<Faculty> Faculties2 { get; set; }
    }
}
