//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AnnualCourseRecord
    {
        public int annualCourseRecordId { get; set; }
        public Nullable<int> annualCourseId { get; set; }
        [Required]
        [Display(Name="Fail Count")]
        public Nullable<int> failCount { get; set; }
        [Required]
        [Display(Name="Pass Count")]
        public Nullable<int> passCount { get; set; }
        [Required]
        [Display(Name="Credit Count")]
        public Nullable<int> creditCount { get; set; }
        [Required]
        [Display(Name="Dist Count")]
        public Nullable<int> distinctionCount { get; set; }
        [Display(Name="Evaluation")]
        public string evaluation { get; set; }
        public Nullable<int> approveStatusId { get; set; }
    
        public virtual AnnualCourse AnnualCourse { get; set; }
        public virtual ApproveStatu ApproveStatu { get; set; }
    }
}
