//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ApproveStatu
    {
        public ApproveStatu()
        {
            this.AnnualCourseRecords = new HashSet<AnnualCourseRecord>();
        }
    
        public int approveStatusId { get; set; }
        [Display(Name="Status")]
        public string name { get; set; }
    
        public virtual ICollection<AnnualCourseRecord> AnnualCourseRecords { get; set; }
    }
}
