//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAnnualCourse
    {
        public int Id { get; set; }
        public Nullable<int> CLId { get; set; }
        public Nullable<int> annualCourseId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AnnualCourse AnnualCourse { get; set; }
    }
}
