//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentId { get; set; }
        public string content { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<int> monitoringReportId { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual CourseMonitoringReport CourseMonitoringReport { get; set; }
    }
}
