//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataTypeAttribute(typeof(CourseMD))]
    public partial class Course
    {
        public Course()
        {
            this.AnnualCourses = new HashSet<AnnualCourse>();
        }
    
        public int courseId { get; set; }
        public string courseName { get; set; }
        public Nullable<int> facultyId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<AnnualCourse> AnnualCourses { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
