//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMonitoringReport
    {
        public int CourseMonitoringReportId { get; set; }
        public Nullable<int> annualCourseId { get; set; }
        public Nullable<int> failCount { get; set; }
        public Nullable<int> passCount { get; set; }
        public Nullable<int> creditCount { get; set; }
        public Nullable<int> distinctionCount { get; set; }
        public string evaluation { get; set; }
        public Nullable<int> approveStatusId { get; set; }
    
        public virtual AnnualCourse AnnualCourse { get; set; }
        public virtual ApproveStatu ApproveStatu { get; set; }
    }
}
