//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int facultyId { get; set; }
        public string facultyName { get; set; }
        public Nullable<int> pvcAccount { get; set; }
        public Nullable<int> dltAccount { get; set; }
        public Nullable<int> cmAccount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
