//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportType
    {
        public ReportType()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int reportTypeId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
