//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int reportId { get; set; }
        public Nullable<int> reportTypeId { get; set; }
        public Nullable<int> approveStatusId { get; set; }
        public Nullable<int> annualCourseId { get; set; }
    
        public virtual AnnualCourse AnnualCourse { get; set; }
        public virtual ApproveStatu ApproveStatu { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
